import type { Metadata } from "next";
// import { createContext } from "react";
// "Creating a context here will cause a error Instead import it from ThemeProvider.tsx"

import { ThemeProvider } from "./components/ThemeProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// type Theme = {
//   colors: {
//     primary: string;
//     secondary: string;
//   };
// };

// const defaultTheme: Theme = {
//   colors: {
//     primary: "#007bff",
//     secondary: "#6c767d",
//   },
// };

// const ThemeContext = createContext<Theme>(defaultTheme);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        {/* <ThemeContext.Provider value={defaultTheme}> */}
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
        {/* </ThemeContext.Provider> */}
      </ThemeProvider>
    </html>
  );
}
